vars:
  CI_BUILD_NUMBER:
    default: 30504
  VERSION_NUMBER:
    default: "0.1.10"

platforms:
  ios:
    version: $VERSION_NUMBER
    buildNumber: $CI_BUILD_NUMBER
  android:
    versionName: $VERSION_NUMBER
    versionCode: $CI_BUILD_NUMBER