[build.environment]
  NODE_VERSION = "18"

[build]
  publish = "dist"
  command = "pnpm build && pnpm generate:node_serverless"

[[redirects]]
  from = '/.well-known/*'
  status = 200
  to = '/deepLink/:splat'

[[redirects]]
  from = "/api/auto_update"
  to = "/.netlify/functions/updates"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin"

[[headers]]
  for = "/api/*"
  [headers.values]
    cache-control = "public, s-max-age=60"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

# auto egde generate
