[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "14"

[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build && npm run generate:node_serverless"

[[redirects]]
  from = "/api/auto_update"
  to = "/.netlify/functions/updates"
  status = 200

[[redirects]]
  from = "/api-edge/auto_update"
  to = "/.netlify/functions/updates"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    cache-control = "public, s-max-age=60"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

# auto egde generate
